[server]
headless = true
enableCORS = false
port = 8545


[theme]
primaryColor = "#1976D2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"
font = "sans serif"


[global]
logging = "info"
